Add room member
wechaty/wechaty pull request #2147
Opened 2021-03-05 10:57 UTC by su-chang

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added
- [ ] CI has been passed. (GitHub actions all turns green)
- [ ] SLA has been signed

## Description

> please describe the changes that you are making, with the related issue number.

2021-03-05 13:14 UTC, huan commented on src/user/friendship.ts
> +  FriendshipAddOptions,
`FriendshipAddOptions as PuppetFriendshipAddOptions`

2021-03-05 13:14 UTC, huan commented on src/user/friendship.ts
> +interface FriendshipAddOptionsObj {
FriendshipAddOptionsObj -> FriendshipAddOptions

2021-03-05 13:19 UTC, huan requested changes
It will be good if we can remove the `string` type in the Puppet definition.

2021-03-05 13:19 UTC, huan commented on src/user/friendship.ts
> +    if (typeof option === 'string') {
```ts
if (typeof options === 'string') {
  await this.wechaty.puppet.friendshipAdd(contact.id, { hello: options })
}
```

2021-03-05 13:19 UTC, huan commented on src/user/friendship.ts
> +        contactId: option.contact && option.contact.id,
`contactId: option?.contact?.id,`

2021-03-09 02:59 UTC, su-chang commented
> It will be good if we can remove the `string` type in the Puppet definition.

I think it should be removed after all puppet has updated.

2021-03-18 08:20 UTC, windmemory commented
> It will be good if we can remove the `string` type in the Puppet definition.

@huan How about we print out a `warn` log with deprecate messages in it, then remove the `string` type in the next version? Thus this will be a smooth transition for our developres.

2021-03-18 08:40 UTC, huan commented
Thanks for the suggestion, I'm ok with that.

Please go ahead and I will modify it as I need after you approved it.

2021-03-18 08:43 UTC, windmemory approved these changes

2021-03-18 14:18 UTC, huan requested changes
Thanks for the Approvement!

Please:

1. Bump the minor version number, whenever the core dependencies (like wechaty-puppet, wechaty-puppet-service, etc) have a minor version bumping.
2. Please make the CI green, or let me know if you have any problems need help.

2021-03-19 03:53 UTC, su-chang commented
Related issue: https://github.com/wechaty/wechaty/issues/2142

2021-03-19 12:13 UTC, su-chang commented
Merge this feature to master branch.

2021-03-19 13:35 UTC, huan approved these changes
LGTM

2021-03-19 13:36 UTC, merged