Conversation read mark
wechaty/wechaty pull request #2207
Opened 2021-07-13 03:09 UTC by su-chang

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added
- [ ] CI has been passed. (GitHub actions all turns green)
- [ ] CLA has been signed

## Description

> please describe the changes that you are making, with the related issue number.

2021-07-13 03:11 UTC, su-chang commented
Related issue: #2166

2021-07-22 08:44 UTC, huan requested changes

2021-07-22 08:44 UTC, huan commented on src/user/contact.ts
> +    try {
Please make the semantic to be clearer:

```ts
if (typeof hasRead === 'undefined') {
  return this.wechaty.puppet.conversationReadMark(this.id)
} else {
  await this.wechaty.puppet.conversationReadMark(this.id, hasRead)
}
```

2021-07-22 08:44 UTC, huan commented on src/user/contact.ts
> +  public async readMark (hasRead?: boolean): Promise<void | boolean> {
Please add overload method definations:

```ts
  async readMark (hasRead: boolean): Promise<void>
  async readMark (): Promise<boolean>
```

2021-07-22 08:44 UTC, huan commented on src/user/room.ts
> +  public async readMark (hasRead?: boolean): Promise<void | boolean> {
The same with message reviews.

2021-07-22 10:26 UTC, huan approved these changes
Awesome, thank you very much for the enhancements!

2021-07-22 10:26 UTC, merged