blue-tape -> node-tap
wechaty/wechaty pull request #2223
Opened 2021-07-29 11:48 UTC by bung87

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added
- [x] CI has been passed. (GitHub actions all turns green)
- [x] CLA has been signed

## Description

>  blue-tape is deprecated.

2021-07-29 11:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty?pullRequest=2223) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty?pullRequest=2223) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty?pullRequest=2223) it.</sub>

2021-08-12 05:04 UTC, huan commented
Thank you for the contrinbution.

However, I can not understand it, so could you please explain why you submit this PR?

What's the problem with the current version of code, and what solution you are trying to make?

2021-08-12 05:13 UTC, bung87 commented
blue-tape is deprecated, and it relys on tape, instead of use tape with node-tap, I think only use node-tap is fine.

2021-08-12 12:44 UTC, huan requested changes
LGTM if the `blue-tap` has been deprecated.

Please help me to understand you by replying to my two comments, resolve the conflicts, and then I believe we can continue to review them.

Thanks!

2021-08-12 12:44 UTC, huan commented on tsconfig.json
> +    "esModuleInterop": true,
I believe those three options you added have already been set in `@chatie/tsconfig`.

Could you please confirm it and remove those additional settings if possible?

2021-08-12 12:44 UTC, huan commented on .eslintrc.js
> +  "@typescript-eslint/no-floating-promises":"off"
Could you please explain why you disable the `no-floating-promises`?

I believe it is very helpful when we coding and missed the `await` in the `if` closure.

2021-08-13 00:19 UTC, huan requested changes
Thanks for following my review comments!

There are some more issues need to be fixed in this PR, please fix them before we can continue reviewing it.

2021-08-13 00:19 UTC, huan commented on .eslintrc.js
> +
Please remove unrelated changes.

2021-08-13 00:19 UTC, huan commented on package.json
> +    "lint:es": "eslint --fix --ignore-pattern node_modules/ --ignore-pattern fixtures/ --ignore-pattern \"**/*.spec.ts\"  \"{bin,examples,src,scripts}/**/*.ts\"",
Please do not use '--fix' implicitly.

If you feel need to add a fix script, I will be good to add a 'lint:fix'

2021-08-13 00:19 UTC, huan commented on package.json
> +    "test:lint": "npm-run-all check-node-version test:lint:es lint:ts lint:sh lint:md",
Please keep the 'lint' prefix instead of changing to 'test' because all wechaty projects are following this name convention

2021-08-13 00:19 UTC, huan commented on src/user/room.spec.ts
> +/* eslint-disable @typescript-eslint/no-floating-promises */
Please remove the disable line.

Fix the exactly problem if there's any.

2021-08-13 00:19 UTC, huan commented on tests/.eslintrc.js
> +  "@typescript-eslint/no-floating-promises":"off"
This file is unnecessary to be added.

Fix the exactly problem if there's any.

2021-08-14 06:30 UTC, huan requested changes
Thanks for the updates!

I noticed that we have `void` before tests and I have reproduced the problems if we remove them.

We should find a better way to avoid to add `void` in our tests.

2021-08-14 06:45 UTC, huan approved these changes
LGTM

Thank you very much for all the great works for converting the Wechaty testing framework from `blue-tape` to the latest version of `tap`!

It seems that we still have some issues about the `tap` and also need some improvement, but this PR can be merged for now.

Appreciate it!

2021-08-14 06:45 UTC, merged

2021-08-14 06:46 UTC, bung87 commented
> Thanks for the updates!
> 
> I noticed that we have `void` before tests and I have reproduced the problems if we remove them.
> 
> We need to find a better way to avoid adding `void` in our tests.

I haven't found a better solution to resolve the problem , as these test use callback style with async function, if there's one that requires more code change I think.

2021-08-14 06:47 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited Bung to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!